.TH cmips 1
.SH NAME
cmips \- A MIPS emulator
.SH SYNOPSIS
.B cmips
.RI [ options ]
.SH DESCRIPTION
A MIPS emulator written in C
.SH OPTIONS
.TP
.BI \-h,\ \-\-help
Output a brief help message.
.TP
.BI \-v,\ \-\-version
Display program version information
.TP
.BI \-q,\ \-\-quiet
Silence any screen output that's not from the running program
.TP
.BI \-n,\ \-\-no\-input
Skip input prompt
.TP
.BI \-r,\ \-\-run
Run loaded program and exit
.TP
.BI \-s,\ \-\-script\ <filename>
Run each command in the script file and exit
.SH BUGS
If you find a bug, please report it at
.br
<\fBhttp://github.com/DSMan195276/cmips\fP>.
.SH AUTHORS
Matt Kilgore <mattkilgore12@gmail.com>
